dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then if_sphinx=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then if_sphinx=:; fi
install:
- pip install pydiatra $pyflakes
- $if_sphinx pip install sphinx
script:
- python -m pydiatra .
- pyflakes .
- $if_sphinx python setup.py build_doc
- LC_ALL=C python setup.py --version
- python setup.py install
- cd /
- python -c 'import keyboardleds'
- curl -fsS https://pypi.org/simple/keyboardleds/; [ $? -eq 22 ]

# vim:ts=2 sts=2 sw=2 et
