language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6-dev"
- "3.7-dev"
install:
- pip install sphinx
script:
- python -m compileall -f .
- \[ "$TRAVIS_PYTHON_VERSION" = "2.6" ] || \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || \[ "$TRAVIS_PYTHON_VERSION" = "3.3" ] || use_sphinx=yes
- \[ -z "$use_sphinx" ] || python setup.py build_doc

# vim:ts=2 sts=2 sw=2 et
